server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:4306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  level:
    root: info

api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secret_key: c546dfe71fe6a1a11609a3ca0394f6d6ef0f9105644a881390c7f2fcf29cfcb1

